CREATE DATABASE medical_ai;

USE medical_ai;

CREATE TABLE users(
 id INT PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR(100),
 email VARCHAR(100) UNIQUE,
 password VARCHAR(255),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reports(
 id INT PRIMARY KEY AUTO_INCREMENT,
 user_id INT,
 report_name VARCHAR(255),
 analysis TEXT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);